version: "3.9"  # optional since v1.27.0
services:
  backend:
    container_name: backend
    build:
      context: ./backend
    volumes:
      - ./backend:/backend
    ports:
      - "80:80"
    command: uvicorn server:app --host 0.0.0.0 --port 80
    extra_hosts:
    - "host.docker.internal:host-gateway"
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    volumes:
      - './frontend:/frontend'
    ports:
      - "8501:8501"
    command: streamlit run app.py
    extra_hosts:
    - "host.docker.internal:host-gateway"