version: "3.9"  # optional since v1.27.0
services:
  backend:
    container_name: backend
    build:
      context: ./backend
    working_dir: /app/app
    volumes:
      - ./backend:/app
    ports:
      - "80:80"
    # command: uvicorn server:app --host 0.0.0.0 --port 80 --reload
    command: gunicorn server:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:80 --keep-alive 30
    extra_hosts:
    - "host.docker.internal:host-gateway"

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    working_dir: /app/app
    depends_on:
      - backend
    volumes:
      - './frontend:/app'
    ports:
      - "8501:8501"
    command: streamlit run Home.py
    extra_hosts:
    - "host.docker.internal:host-gateway"