version: "3.9"  # optional since v1.27.0
services:
  backend:
    build: backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - './frontend:/frontend'
    ports:
      - 3000:3000
    stdin_open: true
    command: npm start