name: CI Workflow

on:
  push:
    branches: 
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 80:80
          - 8501:8501

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Login to DockerHub (Optional: If you want to push images to DockerHub)
    # - name: Login to DockerHub
    #   uses: docker/login-action@v1 
    #   with:
    #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
    #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    # Build and run docker-compose
    - name: Run docker-compose up
      run: |
        docker-compose -f docker-compose.yml up -d

    # Run the tests (I'm assuming you have a script to run tests. Replace with your test command.)
    - name: Run tests
      run: |
        docker-compose exec backend pytest 

    # Shut down the services
    - name: Shutdown
      run: docker-compose down
